out_dir: results_final
metric_best: accuracy

wandb:
  use: False
  project: rfid

dataset:
  format: RFID
  name: rfid
  dir: c:\Users\PC\Desktop\AL\ICML\GNNPlus-main\RFIDDataSet
  task: graph
  task_type: classification
  transductive: False
  split_mode: lopo
  node_encoder: False
  edge_encoder: False
  edge_dim: 8  # Pair Identity (4) + Delta Summary (4)

run_multiple_splits: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100

model:
  type: custom_gnn
  loss_fun: cross_entropy
  graph_pooling: mean

gnn:
  head: mlp_graph
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 2
  dim_inner: 128
  layer_type: gcne
  act: relu
  dropout: 0.2
  residual: False
  ffn: True

optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 150
